---
- name: Adiciona php5 apt-repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
  become: yes

- name: 'Instalar pacodes de dependecia do sistema operacional'
  apt: 
    name: 
      - mysql-server-5.7
      - python3-mysqldb
    state: latest
  become: yes

- name: 'Cria o banco do MySQL'
  mysql_db:
    name: '{{ wp_db_name }}'
    login_user: root
    state: present
  become: yes

- name: 'Cria o usuario do MySQL'
  mysql_user:
    name: "{{ wp_username }}"
    password: "{{ wp_user_password}}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: '{{ item }}'
  become: yes
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - '{{ wp_host_ip }}'

- name: 'Configura MySQL para aceitar conex√µes remotas'
  copy:
    src: '/vagrant/config/roles/mysql/files/my.cnf'
    dest: '/etc/mysql/my.cnf'
    remote_src: yes
  become: yes
  notify:
    - restart mysql