---
- hosts: database

  vars_files:
    - /vagrant/group_vars/all.yml
    - /vagrant/group_vars/database.yml

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: Adiciona php5 apt-repository
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
      become: yes

    - name: 'Instalar pacodes de dependecia do sistema operacional'
      apt: 
        name: 
          - mysql-server-5.7
          - python3-mysqldb
        state: latest
      become: yes

    - name: 'Cria o banco do MySQL'
      mysql_db:
        name: '{{ wp_db_name }}'
        login_user: root
        state: present
      become: yes

    - name: 'Cria o usuario do MySQL'
      mysql_user:
        name: "{{ wp_username }}"
        password: "{{ wp_user_password}}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: '{{ item }}'
      become: yes
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '{{ wp_host_ip }}'
    
    - name: 'Configura MySQL para aceitar conexões remotas'
      copy:
        src: '/vagrant/files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes
      notify:
        - restart mysql

- hosts: wordpress

  vars_files:
    - /vagrant/group_vars/all.yml
    - /vagrant/group_vars/wordpress.yml

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: Adiciona php5 apt-repository
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
      become: yes

    - name: 'Instalar pacodes de dependecia do sistema operacional'
      apt: 
        name: 
          - php5.6
          - apache2 
          - libapache2-mod-php5.6
          - php5.6-gd
          # - libssh2-php
          - php-ssh2
          - php5.6-mcrypt
          - php5.6-mysql
        state: latest
      become: yes

    - name: 'Baixa o arquivo de instação do Wordpress'
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descompactar o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes
    
    - name: 'Copiar blau pro tirosbango'
      copy:
        src: '{{ wp_installation_dir }}/wp-config-sample.php'
        dest: '{{ wp_installation_dir }}/wp-config.php'
        remote_src: yes
      become: yes
      
    - name: 'Configura o wp-config com as entradas do banco de dados'
      replace:
        path: '{{ wp_installation_dir }}/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
        - { regex: 'username_here', value: "{{ wp_username }}" }
        - { regex: 'password_here', value: "{{ wp_user_password}}" }
        - { regex: 'localhost', value: "{{ wp_db_ip }}" }
      become: yes

    - name: 'Configura Apache para servir o Wordpress'
      copy:
        src: '/vagrant/files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify: 
        - restart apache